sonar.projectKey=proyecto-angular
sonar.projectName=Proyecto Angular
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/environment.ts
sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqa_6f52aa21340c3a4ecba4bbbd3526b9c47dba1168
# sonar.password=admin
